project_id = "bszgkwlveddpajjpvbqh"

[functions.send-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.analyze-document]
verify_jwt = true

[functions.analyze-assessment]
verify_jwt = true
